### ISSUE TITLE
Randomly getting kicked-off the awareness bar

### ISSUE THREAD

**Issue by basicNew** [adamantivm/webogram#3]
Sometimes I find myself alone in the awareness bar. Reloading the app bring everybody back.

Two interesting things in the js console:

```
Failed to load resource: net::ERR_NETWORK_CHANGED https://pluto.web.telegram.org/apiw1
```

many `Sending ping after 1 avoided pings.`

**Comment by manzato** [comment]
I believe this is not happening anymore, right @basicNew ? Can we close it?

**Comment by basicNew** [comment]
Yup, sorry
