### ISSUE TITLE
Sometimes desktop notifications don't auto-close

### ISSUE THREAD

**Issue by basicNew** [adamantivm/webogram#4]
They just stay there forever and I have to close them manually

**Comment by adamantivm** [comment]
This is also Webogram-specific

**Comment by basicNew** [comment]
agreed on both issues, but it does impact on us when you look at it as a immedia-replacement. IMO we should find a way out and not just close the issues.

**Comment by adamantivm** [comment]
I would rather focus on issues that we can actually work on, specific to our contribution, at least until our contribution is reasonably solid.
